# Generated by Django 5.2 on 2025-05-12 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('instructor', 'Instructor'), ('project_manager', 'Project Manager'), ('content_creator', 'Content Creator'), ('reviewer', 'Reviewer'), ('editor', 'Editor'), ('ceo', 'CEO'), ('social_media_manager', 'Social Media Manager'), ('hr_manager', 'HR Manager'), ('marketing_head', 'Marketing Head'), ('sales_head', 'Sales Head'), ('finance_head', 'Finance Head')], max_length=50)),
                ('working_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('resigned', 'Resigned')], default='active', max_length=50)),
                ('work_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=50)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='team_members/profile_images/%Y/%m/%d/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
                'db_table': 'team_member',
                'ordering': ['-created_at'],
            },
        ),
    ]
